/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMySuggestionsRouteImport } from './routes/_authenticated/my-suggestions'
import { Route as AuthenticatedMyProgressRouteImport } from './routes/_authenticated/my-progress'
import { Route as AuthenticatedMyFeedbackRouteImport } from './routes/_authenticated/my-feedback'
import { Route as AuthenticatedMyCoursesRouteImport } from './routes/_authenticated/my-courses'
import { Route as AuthenticatedMyCertificatesRouteImport } from './routes/_authenticated/my-certificates'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedTeamSuggestionsRouteImport } from './routes/_authenticated/team/suggestions'
import { Route as AuthenticatedTeamProgressRouteImport } from './routes/_authenticated/team/progress'
import { Route as AuthenticatedTeamMembersRouteImport } from './routes/_authenticated/team/members'
import { Route as AuthenticatedTeamAssignmentsRouteImport } from './routes/_authenticated/team/assignments'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTeamsRouteImport } from './routes/_authenticated/admin/teams'
import { Route as AuthenticatedAdminTeamsIndexRouteImport } from './routes/_authenticated/admin/teams.index'
import { Route as AuthenticatedAdminTeamsTeamIdMembersRouteImport } from './routes/_authenticated/admin/teams.$teamId.members'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMySuggestionsRoute =
  AuthenticatedMySuggestionsRouteImport.update({
    id: '/my-suggestions',
    path: '/my-suggestions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyProgressRoute = AuthenticatedMyProgressRouteImport.update({
  id: '/my-progress',
  path: '/my-progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyFeedbackRoute = AuthenticatedMyFeedbackRouteImport.update({
  id: '/my-feedback',
  path: '/my-feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyCoursesRoute = AuthenticatedMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyCertificatesRoute =
  AuthenticatedMyCertificatesRouteImport.update({
    id: '/my-certificates',
    path: '/my-certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamSuggestionsRoute =
  AuthenticatedTeamSuggestionsRouteImport.update({
    id: '/team/suggestions',
    path: '/team/suggestions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamProgressRoute =
  AuthenticatedTeamProgressRouteImport.update({
    id: '/team/progress',
    path: '/team/progress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamMembersRoute =
  AuthenticatedTeamMembersRouteImport.update({
    id: '/team/members',
    path: '/team/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamAssignmentsRoute =
  AuthenticatedTeamAssignmentsRouteImport.update({
    id: '/team/assignments',
    path: '/team/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTeamsRoute = AuthenticatedAdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTeamsIndexRoute =
  AuthenticatedAdminTeamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminTeamsRoute,
  } as any)
const AuthenticatedAdminTeamsTeamIdMembersRoute =
  AuthenticatedAdminTeamsTeamIdMembersRouteImport.update({
    id: '/$teamId/members',
    path: '/$teamId/members',
    getParentRoute: () => AuthenticatedAdminTeamsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof authSignInRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/my-certificates': typeof AuthenticatedMyCertificatesRoute
  '/my-courses': typeof AuthenticatedMyCoursesRoute
  '/my-feedback': typeof AuthenticatedMyFeedbackRoute
  '/my-progress': typeof AuthenticatedMyProgressRoute
  '/my-suggestions': typeof AuthenticatedMySuggestionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/team/assignments': typeof AuthenticatedTeamAssignmentsRoute
  '/team/members': typeof AuthenticatedTeamMembersRoute
  '/team/progress': typeof AuthenticatedTeamProgressRoute
  '/team/suggestions': typeof AuthenticatedTeamSuggestionsRoute
  '/admin/teams/': typeof AuthenticatedAdminTeamsIndexRoute
  '/admin/teams/$teamId/members': typeof AuthenticatedAdminTeamsTeamIdMembersRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/my-certificates': typeof AuthenticatedMyCertificatesRoute
  '/my-courses': typeof AuthenticatedMyCoursesRoute
  '/my-feedback': typeof AuthenticatedMyFeedbackRoute
  '/my-progress': typeof AuthenticatedMyProgressRoute
  '/my-suggestions': typeof AuthenticatedMySuggestionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/team/assignments': typeof AuthenticatedTeamAssignmentsRoute
  '/team/members': typeof AuthenticatedTeamMembersRoute
  '/team/progress': typeof AuthenticatedTeamProgressRoute
  '/team/suggestions': typeof AuthenticatedTeamSuggestionsRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsIndexRoute
  '/admin/teams/$teamId/members': typeof AuthenticatedAdminTeamsTeamIdMembersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/my-certificates': typeof AuthenticatedMyCertificatesRoute
  '/_authenticated/my-courses': typeof AuthenticatedMyCoursesRoute
  '/_authenticated/my-feedback': typeof AuthenticatedMyFeedbackRoute
  '/_authenticated/my-progress': typeof AuthenticatedMyProgressRoute
  '/_authenticated/my-suggestions': typeof AuthenticatedMySuggestionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/teams': typeof AuthenticatedAdminTeamsRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/team/assignments': typeof AuthenticatedTeamAssignmentsRoute
  '/_authenticated/team/members': typeof AuthenticatedTeamMembersRoute
  '/_authenticated/team/progress': typeof AuthenticatedTeamProgressRoute
  '/_authenticated/team/suggestions': typeof AuthenticatedTeamSuggestionsRoute
  '/_authenticated/admin/teams/': typeof AuthenticatedAdminTeamsIndexRoute
  '/_authenticated/admin/teams/$teamId/members': typeof AuthenticatedAdminTeamsTeamIdMembersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/catalog'
    | '/courses'
    | '/my-certificates'
    | '/my-courses'
    | '/my-feedback'
    | '/my-progress'
    | '/my-suggestions'
    | '/settings'
    | '/'
    | '/admin/teams'
    | '/admin/users'
    | '/team/assignments'
    | '/team/members'
    | '/team/progress'
    | '/team/suggestions'
    | '/admin/teams/'
    | '/admin/teams/$teamId/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/catalog'
    | '/courses'
    | '/my-certificates'
    | '/my-courses'
    | '/my-feedback'
    | '/my-progress'
    | '/my-suggestions'
    | '/settings'
    | '/'
    | '/admin/users'
    | '/team/assignments'
    | '/team/members'
    | '/team/progress'
    | '/team/suggestions'
    | '/admin/teams'
    | '/admin/teams/$teamId/members'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/_authenticated/catalog'
    | '/_authenticated/courses'
    | '/_authenticated/my-certificates'
    | '/_authenticated/my-courses'
    | '/_authenticated/my-feedback'
    | '/_authenticated/my-progress'
    | '/_authenticated/my-suggestions'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/admin/teams'
    | '/_authenticated/admin/users'
    | '/_authenticated/team/assignments'
    | '/_authenticated/team/members'
    | '/_authenticated/team/progress'
    | '/_authenticated/team/suggestions'
    | '/_authenticated/admin/teams/'
    | '/_authenticated/admin/teams/$teamId/members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-suggestions': {
      id: '/_authenticated/my-suggestions'
      path: '/my-suggestions'
      fullPath: '/my-suggestions'
      preLoaderRoute: typeof AuthenticatedMySuggestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-progress': {
      id: '/_authenticated/my-progress'
      path: '/my-progress'
      fullPath: '/my-progress'
      preLoaderRoute: typeof AuthenticatedMyProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-feedback': {
      id: '/_authenticated/my-feedback'
      path: '/my-feedback'
      fullPath: '/my-feedback'
      preLoaderRoute: typeof AuthenticatedMyFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-courses': {
      id: '/_authenticated/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof AuthenticatedMyCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-certificates': {
      id: '/_authenticated/my-certificates'
      path: '/my-certificates'
      fullPath: '/my-certificates'
      preLoaderRoute: typeof AuthenticatedMyCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team/suggestions': {
      id: '/_authenticated/team/suggestions'
      path: '/team/suggestions'
      fullPath: '/team/suggestions'
      preLoaderRoute: typeof AuthenticatedTeamSuggestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/progress': {
      id: '/_authenticated/team/progress'
      path: '/team/progress'
      fullPath: '/team/progress'
      preLoaderRoute: typeof AuthenticatedTeamProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/members': {
      id: '/_authenticated/team/members'
      path: '/team/members'
      fullPath: '/team/members'
      preLoaderRoute: typeof AuthenticatedTeamMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/assignments': {
      id: '/_authenticated/team/assignments'
      path: '/team/assignments'
      fullPath: '/team/assignments'
      preLoaderRoute: typeof AuthenticatedTeamAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/teams': {
      id: '/_authenticated/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AuthenticatedAdminTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/teams/': {
      id: '/_authenticated/admin/teams/'
      path: '/'
      fullPath: '/admin/teams/'
      preLoaderRoute: typeof AuthenticatedAdminTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminTeamsRoute
    }
    '/_authenticated/admin/teams/$teamId/members': {
      id: '/_authenticated/admin/teams/$teamId/members'
      path: '/$teamId/members'
      fullPath: '/admin/teams/$teamId/members'
      preLoaderRoute: typeof AuthenticatedAdminTeamsTeamIdMembersRouteImport
      parentRoute: typeof AuthenticatedAdminTeamsRoute
    }
  }
}

interface AuthenticatedAdminTeamsRouteChildren {
  AuthenticatedAdminTeamsIndexRoute: typeof AuthenticatedAdminTeamsIndexRoute
  AuthenticatedAdminTeamsTeamIdMembersRoute: typeof AuthenticatedAdminTeamsTeamIdMembersRoute
}

const AuthenticatedAdminTeamsRouteChildren: AuthenticatedAdminTeamsRouteChildren =
  {
    AuthenticatedAdminTeamsIndexRoute: AuthenticatedAdminTeamsIndexRoute,
    AuthenticatedAdminTeamsTeamIdMembersRoute:
      AuthenticatedAdminTeamsTeamIdMembersRoute,
  }

const AuthenticatedAdminTeamsRouteWithChildren =
  AuthenticatedAdminTeamsRoute._addFileChildren(
    AuthenticatedAdminTeamsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedMyCertificatesRoute: typeof AuthenticatedMyCertificatesRoute
  AuthenticatedMyCoursesRoute: typeof AuthenticatedMyCoursesRoute
  AuthenticatedMyFeedbackRoute: typeof AuthenticatedMyFeedbackRoute
  AuthenticatedMyProgressRoute: typeof AuthenticatedMyProgressRoute
  AuthenticatedMySuggestionsRoute: typeof AuthenticatedMySuggestionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminTeamsRoute: typeof AuthenticatedAdminTeamsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedTeamAssignmentsRoute: typeof AuthenticatedTeamAssignmentsRoute
  AuthenticatedTeamMembersRoute: typeof AuthenticatedTeamMembersRoute
  AuthenticatedTeamProgressRoute: typeof AuthenticatedTeamProgressRoute
  AuthenticatedTeamSuggestionsRoute: typeof AuthenticatedTeamSuggestionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedMyCertificatesRoute: AuthenticatedMyCertificatesRoute,
  AuthenticatedMyCoursesRoute: AuthenticatedMyCoursesRoute,
  AuthenticatedMyFeedbackRoute: AuthenticatedMyFeedbackRoute,
  AuthenticatedMyProgressRoute: AuthenticatedMyProgressRoute,
  AuthenticatedMySuggestionsRoute: AuthenticatedMySuggestionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminTeamsRoute: AuthenticatedAdminTeamsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedTeamAssignmentsRoute: AuthenticatedTeamAssignmentsRoute,
  AuthenticatedTeamMembersRoute: AuthenticatedTeamMembersRoute,
  AuthenticatedTeamProgressRoute: AuthenticatedTeamProgressRoute,
  AuthenticatedTeamSuggestionsRoute: AuthenticatedTeamSuggestionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
